### ISSUE TITLE
VICTORY HAND emoji doesn't have emoji modifiers

### ISSUE THREAD

**Issue by yantene** [iamcal/emoji-data#105]
In previous version, VICTORY HAND emoji had emoji modifiers.
What's the reason?

**Comment by yantene** [comment]
The following emoji modifier seems to disappear.

- weight_lifter
- golfer
- man_in_business_suit_levitating
- sleuth_or_spy
- raised_hand_with_fingers_splayed
- point_up
- person_with_ball
- v
- writing_hand

**Comment by iamcal** [comment]
Do you mean the variation selector U+FE0F? Those are now conforming to the Unicode 10 / Emoji 5 spec. The main codepoint includes a variation selector where appropriate and a `non_qualified` version without it.

**Comment by yantene** [comment]
Thank you for your reply.

I mean skin color modifier.
Although I think that the emojis should have skin color,
They don't have it.

**Comment by iamcal** [comment]
good catch - i'm looking into why these are missing

**Comment by iamcal** [comment]
this was related to non-qualified/fully-qualified codepoints. the 9 you noted use fully qualified forms (with `-FE0F`) when used alone, but drop the modifier when used with skin tones. this wasn't handled correctly when building the map. i'm fixing this in PR #110 which will also include all the missing images and updated sheets.

**Comment by iamcal** [comment]
now fixed on master and in 4.0.1

no downstream libraries have been updated yet
