### ISSUE TITLE
Add <emoji>-FE0F-<emoji modifier>

### ISSUE THREAD

**Issue by yantene** [iamcal/emoji-data#106]
Some environments (probably iPhone?) enter this emoji pattern as same as \<emoji\>-\<emoji modifier\>.
e.g. https://twitter.com/405yuna/status/799270360587739137

**Comment by iamcal** [comment]
this should be present for all emoji sequences that require it. is there a particular emoji/modifier combo you think is incorrect?

**Comment by seiya-git** [comment]
https://docs.google.com/document/d/1pflCUy4NnVHoyZu9WEo9aZ1WfSH-QGrbJBhEvi5t6Xg/edit
Some app have incorrect output for "Gender Emoji ZWJ Sequences", like telegram.
For example 26f9-1f3ff-fe0f-200d-2640-fe0f is Woman Bouncing Ball: Dark Skin Tone

**Comment by iamcal** [comment]
The qualified/non-qualified versions are generated from the Unicode source material, so contain only the official sequences.

To allow matching against badly implemented apps, you can explicitly filter out U+FE0F sequences and match against the `non_qualified` keys.

**Comment by andersk** [comment]
There is a bug here though:

- #217
