### ISSUE TITLE
Commercial usage?

### ISSUE THREAD

**Issue by Vuurvlieg** [iamcal/emoji-data#108]
Thanks for this amazing library!

I want to use this for a commercial project, I know this library is MIT licensed but if I'm not wrong this library is using the images from [emojiOne](https://www.emojione.com/), which needs a `premium license` to allow integration to commercial projects.

So I don't know if I can use your library `emoji-data` for my commercial project, without buying that premium license from emojiOne?

**Comment by iamcal** [comment]
the current version of the emojione images included here are from the older v2.x series which had an attribution license. however, the apple images are definitely not licensed for commercial use. twitter and android images have more straightforward licensing

**Comment by Vuurvlieg** [comment]
Thanks for the clarification!

**Comment by abdelhady** [comment]
@iamcal I think this is definitely worth mentioning in the README.md

**Comment by iamcal** [comment]
good idea - i've added details and links to the readme

https://github.com/iamcal/emoji-data/blob/master/README.md#image-sources
