### ISSUE TITLE
Twemoji 2.4

### ISSUE THREAD

**Issue by Crissov** [iamcal/emoji-data#112]
Twitter has updated some of their emoji graphics in December 2017.

**Comment by iamcal** [comment]
terrible timing 😂 - i'll see if i can update this weekend

**Comment by dominiczaq** [comment]
hi,

Do you have planned date for the next release with updated graphics?
Many thanks for your work!

**Comment by Art4** [comment]
@iamcal Ping?

**Comment by rugk** [comment]
@iamcal Is this still maintained. When do you plan the next release?

**Comment by iamcal** [comment]
Support for Twemoji v12.1.4 is coming in #165

**Comment by iamcal** [comment]
fixed in v5.0.0
