### ISSUE TITLE
Emoji that have aliases in Google set are missing

### ISSUE THREAD

**Issue by jschear** [iamcal/emoji-data#120]
It looks like the Google emoji set aliases a number of codepoints to other codepoints:
https://github.com/googlei18n/noto-emoji/blob/master/emoji_aliases.txt
Some of these aliases are captured by the `obsoleted_by` property, but others aren't.

For these codepoints, the corresponding arrays in `emoji.json` have `"has_img_google": false`, even though the Google noto font will render them. Ideally, these aliases would be followed during the Google build step.

One example is the Clipperton Island Flag (`flag-cp`), which uses the same flag as France: https://emojipedia.org/flag-for-clipperton-island/

**Comment by iamcal** [comment]
Fixed in 4.0.3
