### ISSUE TITLE
Position of The Image in The SpriteSheet

### ISSUE THREAD

**Issue by clarktank** [iamcal/emoji-data#128]
How do you find the position of the image in the spritesheet? For example, the **Ireland Flag** is positioned at **sheet_x: 2** and **sheet_y: 34**, but looking at the [sprite sheet](https://github.com/iamcal/emoji-data/blob/master/sheet_apple_64.png) it doesn't translate to the location of the map.
```
    {
        "name": "Ireland Flag",
        "unified": "1F1EE-1F1EA",
        "non_qualified": null,
        "docomo": null,
        "au": null,
        "softbank": null,
        "google": null,
        "image": "1f1ee-1f1ea.png",
        "sheet_x": 2,
        "sheet_y": 34,
        "short_name": "flag-ie",
        "short_names": [
            "flag-ie"
        ],
        "text": null,
        "texts": null,
        "category": "Flags",
        "sort_order": 114,
        "added_in": "6.0",
        "has_img_apple": true,
        "has_img_google": true,
        "has_img_twitter": true,
        "has_img_emojione": true,
        "has_img_facebook": true,
        "has_img_messenger": true
    },
```

**Comment by clarktank** [comment]
I figured it out!

**Comment by philraj** [comment]
Please write the solution you found when you figure out the answer to your own question so that others can benefit. :)

**Comment by clarktank** [comment]
Oh sorry, basically the origin of sprite starts at the very top left corner. 
x=2 is the third column and y=34 is the 35th row.
