### ISSUE TITLE
issue while showing emoji

### ISSUE THREAD

**Issue by gaut7** [iamcal/emoji-data#129]
@ericost 

Hi guys, I checked demo part of this library and it's awesome. But I am facing some issues while trying to implement the same in my project. I have attached my code below please check and let me know if I am doing anything wrong.

[code.txt](https://github.com/iamcal/emoji-data/files/1646652/code.txt)

**Comment by iamcal** [comment]
Very late response, but this issue is with a different library: https://github.com/iamcal/js-emoji
