### ISSUE TITLE
New WhatsApp Emojis

### ISSUE THREAD

**Issue by ShalokShalom** [iamcal/emoji-data#130]
WhatsApp introduced a [new Emojiset](https://emojipedia.org/whatsapp/).

**Comment by Crissov** [comment]
One can extract the files (at rather low resolution) from web.whatsapp.com, but as far as I can see this requires too be logged in with one’s phone number.

**Comment by Shimmi** [comment]
Hi guys,
I found a repo with all the WhatsApp emojis: https://github.com/eladkarako/whatsapp-emoji
Can this be used?

The emoji on the web.whatsapp.com could be easily programmatically grabbed as they all have the same link: https://web.whatsapp.com/img/88179f049c0d1d26c823d2954ecb54a7_w_e<NUMBER>-64.png
where <NUMBER> is a number from 1 to 2401.
E.g: https://web.whatsapp.com/img/88179f049c0d1d26c823d2954ecb54a7_w_e1483-64.png
Just not sure about the mapping of the numbers to the codes...

Or can images from emojipedia be used? They shall be also pretty easy to grab...

**Comment by Crissov** [comment]
@eladkarako’s repository still has Apple emojis, not the new custom WhatsApp emojis.

**Comment by eladkarako** [comment]
>repository still has Apple emojis, not the new custom WhatsApp emojis.

?

**Comment by eladkarako** [comment]
<h1>Ú︎ᵱ︎ḋ︎ḁ︎të︎ḍ︎<a href="https://github.com/eladkarako/whatsapp-emoji"><br/><img src="http://eladkarako.com/whatsapp-emoji/resources/e2149.png"/></a></h1>

**Comment by ShalokShalom** [comment]
Thanks a lot ^-^

**Comment by rugk** [comment]
Duplicate of https://github.com/iamcal/emoji-data/issues/102

**Comment by iamcal** [comment]
Closing as a duplicate
