### ISSUE TITLE
request: Twitter Color Emoji

### ISSUE THREAD

**Issue by eladkarako** [iamcal/emoji-data#133]
You have EmojiOne sheet,
any chance of a  Twitter Color Emoji one too?

I found this rep <a href="https://github.com/eosrei/twemoji-color-font">Twitter Color Emoji SVGinOT Font</a> that may be used, there are raw images under <a href="https://github.com/eosrei/twemoji-color-font/tree/master/assets/twemoji-svg">assets/twemoji-svg</a>.

It should be newer and better than EmojiOne, using Twitter's Unicode-10 emoji with diversity and country flags.

**Comment by tankerkiller125** [comment]
The twitter emojis are already included here in their PNG format.
