### ISSUE TITLE
female_sign and male_sign not present in apple, messenger and emojione.

### ISSUE THREAD

**Issue by kercos** [iamcal/emoji-data#136]
2640-fe0f.png (female_sign) and 2642-fe0f.png (male_sign) not found in apple, messenger and emojione folders. They are present in Googe, Facebook, Twitter.

**Comment by kercos** [comment]
Ok, it seems that these signs are not available for apple, see line 1267 in https://unicode.org/emoji/charts/full-emoji-list.html. 

Anyone knows why this is the case?

**Comment by iamcal** [comment]
Unknown - Apple also chooses not to provide the medical symbol. These are the only 3 missing from Apple images (the other sets are all missing different code points)
