### ISSUE TITLE
Google Noto update

### ISSUE THREAD

**Issue by Extarys** [iamcal/emoji-data#139]
Noto update to change pistol to plastic thing.
"v2018-04-24-pistol-update" https://github.com/googlei18n/noto-emoji/releases

----
I've spent the day trying to understand unicode and how to build my little library but then I discover.. TADA.. your repo. Thank you very much !

**Comment by iamcal** [comment]
Emoji v12.1 is supported in #165

**Comment by iamcal** [comment]
fixed in v5.0.0
