### ISSUE TITLE
Emoji 11

### ISSUE THREAD

**Issue by mark-wade** [iamcal/emoji-data#145]
Can you update for the new Emojis in iOS 12.1 etc?

**Comment by rugk** [comment]
Actually, there is already a PR: https://github.com/iamcal/emoji-data/pull/146

**Comment by iamcal** [comment]
#152 got merged to support emoji/unicode 11

there's not yet a new release containing these changes, but they are available on maste

**Comment by jwheare** [comment]
master was missing some new images, #153 adds them.

**Comment by tsuyoshizawa** [comment]
@iamcal Could you see #153 or build image by yourself? Then, I hope you cut a release for uploading to npm.

**Comment by pederjohnsen** [comment]
Any updates on this? will we see a new release on npm soon with the Emoji 11 set?

**Comment by rugk** [comment]
As requested in https://github.com/missive/emoji-mart/issues/269#issuecomment-551082708, you still need to release the change on npm, @iamcal?
Could you please do so?

**Comment by rugk** [comment]
Sorry, but are there any news?

**Comment by iamcal** [comment]
Emoji v12.1 is supported in #165

**Comment by iamcal** [comment]
fixed in v5.0.0
