### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by onassar** [iamcal/emoji-data#155]
You mind compiling a new release that has `HEAD`?

**Comment by lucidtheory** [comment]
Please cut a release. Lots of good stuff on master that can not be used because master is over 4GB large

**Comment by iamcal** [comment]
I'm working on v12 support in #165 which will have a release cut when complete. Master unfortunately is missing a ton of Apple images due to some bugs

**Comment by iamcal** [comment]
fixed in v5.0.0
