### ISSUE TITLE
Please explain nomencalture of sheet names

### ISSUE THREAD

**Issue by adeopura4** [iamcal/emoji-data#158]
I am new to this, could you please explain the nomenclature of the sheet. For instance, I see a sheet named "sheet_twitter_16_indexed_128.png". I assume this is the sheet created from twitter emojis, the emojis are 16px by 16px in size. Is that correct? What does indexed mean in this regard and what does 128 mean?

Thank you for you help and for this wonderful library.

**Comment by iamcal** [comment]
They vary in size by quite a lot:
- `sheet_apple_16.png` - 1.62 MB
- `sheet_apple_16_indexed_256.png` - 346 KB
- `sheet_apple_16_indexed_128.png` - 290 KB

**Comment by iamcal** [comment]
now documented on the v12 branch - see #165
