### ISSUE TITLE
Some emoji missing, some not flagged as being on iOS

### ISSUE THREAD

**Issue by Scraft** [iamcal/emoji-data#161]
I had to remove any checks for "has_img_apple" as there are a lot of emoji flagged as not being available on Apple, when they are very much available on Apple.

Secondly, there are a number of emoji that display as a question mark.

In both cases, these are emoji which are selected by the iOS default keyboard, on the latest OS.

To help, here is a dump of all emoji, **note** I have only used the base skin variation: https://pastebin.com/CFcWDmep it should be relatively easy to take this dump and compare it to what is currently being generated, to highlight all the mistakes in the current data.

**Comment by iamcal** [comment]
This is now fixed under the v12 branch in PR #165 - apple is only missing 3 images, which they choose not to include (male symbol, female symbol and medical symbol)

**Comment by iamcal** [comment]
fixed in v5.0.0
