### ISSUE TITLE
Missing emojis are rendered using Apple's (?) images

### ISSUE THREAD

**Issue by Rohansi** [iamcal/emoji-data#162]
Some missing emoji are rendered using a different set, such as the bagel and mango.

Here's a screenshot of the Google set (32px). These are clearly not from Google's font because the style is very different.
![image](https://user-images.githubusercontent.com/1319884/69968049-a1a27180-14e7-11ea-99ee-7e987c2c5d22.png)

This can be a problem with licensing because those images are more restricted from use than the other Google ones, for example if being used in a commercial product.

**Comment by iamcal** [comment]
If you need to build the sheets without fallback images for missing code points (all the different sets are missing some combination of images), then you can modify the following line in `build/build_image.php` and rebuilt your sheets: https://github.com/iamcal/emoji-data/blob/da7eb2a5ecc7da5e70e40cbd5d20a75d879c67af/build/build_image.php#L62

**Comment by Rohansi** [comment]
If that is the case then you should add a warning message to this section of the README stating that the files included in the repo are not safe to use, and that you should build it yourself with the sets you are legally allowed to use.

https://github.com/iamcal/emoji-data#image-sources

It's very misleading providing image sets labelled as "google" and "twitter", stating that they allow commercial usage, but including Apple's images in those sets means they do not allow commercial usage.

**Comment by iamcal** [comment]
This is a great point - i'm addressing it in #166

**Comment by iamcal** [comment]
v5.0.1 provides the 'clean' sheets and updates the docs to make this more clear
