### ISSUE TITLE
403 when trying to retrieve http://www.unicode.org/~scherer/emoji4unicode/snapshot/full.html

### ISSUE THREAD

**Issue by greysonp** [iamcal/emoji-data#163]
The first step in the build instructions:
`wget http://www.unicode.org/~scherer/emoji4unicode/snapshot/full.html`

Results in a 403. Using archive.org, the most recent functioning snapshot appears to be from March 14, 2018:
https://web.archive.org/web/20180314172610/http://www.unicode.org/~scherer/emoji4unicode/snapshot/full.html

Is there another data source that can be used? I'm interested in updating this emoji set.

**Comment by iamcal** [comment]
you don't need to follow this step anymore - the version included in the repo will work fine (and will not be updated again now).
