### ISSUE TITLE
What about :man-woman-girl-boy: ?

### ISSUE THREAD

**Issue by aaronscherbing** [iamcal/emoji-data#17]
Every other combination of man, woman, girl, and boy is included except :man-woman-girl-boy:

What's going on here?

**Comment by iamcal** [comment]
urgh, looks like i just missed it

**Comment by aaronscherbing** [comment]
Thanks, man!  I really am glad this project exists.  It saved me a bunch of time.

**Comment by iamcal** [comment]
re-opening this because although the data is there, the image is missing. i'm working on fixing extraction to pull out this image shortly

**Comment by iamcal** [comment]
this is now in the data file and in the image sheets.

additionally, i'm now using the newer 10.10.3 apple images, which have different hair for skin type 1
