### ISSUE TITLE
Sort Order different to Apple's

### ISSUE THREAD

**Issue by onato** [iamcal/emoji-data#172]
Where does the sort order come from? It is different from the order in the emoji keyboard on iOS and the Character Viewer in OSX.

Also, where does the category come from? The `jack_o_lantern`, for example, has a `"category" : "Activities"`, but Apple has it in `Smileys & People`.

**Comment by milesj** [comment]
@onato Not sure about this library, but the order is defined by the Unicode spec.

**Comment by onato** [comment]
Apple and this library both have a different order to the Unicode values. I assume this library has taken the arbitrary order from another platform.

**Comment by iamcal** [comment]
Previous versions of this library used the Apple sort order, but we've been using the Unicode sort order since v4.0.1
