### ISSUE TITLE
Cite non-Unicode data sources

### ISSUE THREAD

**Issue by jsejcksn** [iamcal/emoji-data#176]
Hi—thanks for maintaining this lib!

I know the canonical list of core data comes from Unicode, but there are components of this dataset which aren't available there—things like:

- short names / :colon: syntax
- ASCII text variants
- maybe more?

Will you provide documentation in the README for the how this data was / can be obtained?

**Comment by iamcal** [comment]
The data in question came from me, so this repo is the primary source.

**Comment by jsejcksn** [comment]
> The data in question came from me

@iamcal Can you be a little more specific? Did you arbitrarily assign short names/keywords manually based on what came to mind as you went through the entire list? Did you use a systematic guide or other sources for inspiration? etc.

**Comment by iamcal** [comment]
Colon syntax: Invented by Campfire I think

Short names: They were the original set used by Slack in 2013, which was a mix of Unicode official names, campfire aliases, and things that scanned better (as decided by me).

ASCII text variants: Just written by me

**Comment by jsejcksn** [comment]
Thanks for the insight!
