### ISSUE TITLE
null emoji names

### ISSUE THREAD

**Issue by PyICoder** [iamcal/emoji-data#180]
there seems to be alot of null emoji names, especially for the emojis with tones, is there a reason for it?

**Comment by iamcal** [comment]
the `name` field contains Unicode codepoint names, which don't exist for sequences. It's probably reasonable to put the sequence name in there instead though, which I'll work on adding

**Comment by iamcal** [comment]
fixed in e512953312c012f6bd00e3f2ef6bf152ca3710f8, will go into the next release
