### ISSUE TITLE
Duplicate names

### ISSUE THREAD

**Issue by ticky** [iamcal/emoji-data#181]
As of #179, there are two emoji whose short names are not unique;

- `:beetle:`, which refers to both 🪲 U+1FAB2 BEETLE and 🐞 U+1F41E LADY BEETLE
- `:man_in_tuxedo:`, which refers to both 🤵 U+1F935 MAN IN TUXEDO and the sequence 🤵‍♂️ U+1F935 U+200D U+2642 U+FE0F

This makes doing a direct conversion difficult, as looking up a character by short name now has two possible values. This doesn’t seem to have been the case in any prior version of this dataset. Is this a bug?

**Comment by iamcal** [comment]
fixed on master and will go into next release
