### ISSUE TITLE
Include categories in NPM package

### ISSUE THREAD

**Issue by wilg** [iamcal/emoji-data#187]
I don't need the sprite sheets but I do need the categories, seems like a small enough file to include.

**Comment by iamcal** [comment]
good idea. this is now on-trunk for the next release

in the meantime, you can construct `categories.json` directly from the emoji.json data (the `category` and `sort_order` fields)

**Comment by wilg** [comment]
Actually, I should clarify that what I was after was the _sort order of the categories_ – my use case is displaying the emoji categories in the "standard" order (like iOS or Slack does). Unless this is derivable somehow from the existing json? I don't actually need the list of emojis in each.

**Comment by iamcal** [comment]
ahh, that makes sense. that data is not present in emoji.json today.

**Comment by iamcal** [comment]
categories and subcategories (along with their sort order) are now in the `categories.json` file
