### ISSUE TITLE
Potential typo in short names for wo/men with bunny ears

### ISSUE THREAD

**Issue by Merlin2001** [iamcal/emoji-data#189]
I just stumbled across a potential typo with the short names for both WOMEN and MEN WITH BUNNY EARS.  
In both cases, the short names **omit the plural form** and use wo/man instead of wo/men:

```json
{
    "name": "WOMEN WITH BUNNY EARS",
    "short_name": "woman-with-bunny-ears-partying",
    "short_names": [
        "woman-with-bunny-ears-partying"
    ],
},
{
    "name": "MEN WITH BUNNY EARS",
    "short_name": "man-with-bunny-ears-partying",
    "short_names": [
        "man-with-bunny-ears-partying"
    ],
},
```

P.S.: Probably the weirdest issue title I've written so far 🙈

**Comment by iamcal** [comment]
good catch! fixed on master and will go out in the next version. the incorrect/singular names are still there as an alternative
