### ISSUE TITLE
build_map script issues

### ISSUE THREAD

**Issue by fangxg** [iamcal/emoji-data#191]
I try to rebuild the master mapping, so I run the  './download_spec_files.sh’ and 'php build_map.php’. But I will receive the warning count(): Parameter must be an array or an object that implements Countable in emoji-data-master/build/build_map.php on line 996’.Do you know why? My computer is MacBook Pro. And I have installed the optimization tools.

**Comment by iamcal** [comment]
This error was introduced in a recent PHP version. I've now fixed it with commit f7b4458 - if you `git pull` it should work without errors.

**Comment by fangxg** [comment]
Awesome~, thank you very much~
