### ISSUE TITLE
Emojis 13.1 Support

### ISSUE THREAD

**Issue by yagudaev** [iamcal/emoji-data#192]
Thank you 🙏  for making this great library :).

When will [13.1 support](https://emojipedia.org/emoji-13.1/) be out? I would love to start using the new iOS 14.5 set :).

Is there anything I can do to help make that happen?

**Comment by iamcal** [comment]
I need to wait for 13.1 to reach mac OS, so that I can extract the hi-res Apple images. I'm not sire when that's expected

**Comment by yagudaev** [comment]
Thanks for the super quick reply 😊.

They are on the MacOS 11.4 Big Sur as far as I can tell:

![Screen Shot 2021-06-04 at 1 40 54 PM](https://user-images.githubusercontent.com/1386966/120860505-a1e75700-c53a-11eb-9591-0abc4f1ad590.png)

Monday is WWDC, we should get the Beta for MacOS 12 and iOS 15. As far as I remember they usually add additional icons closer to launch in September, but that will be [Emoji Version 14.0](https://emojipedia.org/emoji-14.0/) I believe.

**Comment by iamcal** [comment]
this has now landed on master and will go out in the next release
