### ISSUE TITLE
Wrong emojis

### ISSUE THREAD

**Issue by pedrohenriquebraga** [iamcal/emoji-data#199]
![](https://i.ibb.co/fqfJ3b0/Screenshot-20210620-174053-Expo-Go.jpg)

I'm converting the unified code with 
```js
String.fromCodePoint(parseInt(unified,  16))
``` 
and i'm getting this result (emojis wrong and/or duplicated), how fix it?

**Comment by iamcal** [comment]
Can you share some more of the code that you're using? That's just a fragment of pure JavaScript and doesn't use the data in this library at all.

**Comment by pedrohenriquebraga** [comment]
@iamcal 
```ts
import _ from "lodash";
import emojiSource from "emoji-datasource";

const filteredEmojis = emojiSource.filter((e) => !e.obsoletes && !e.obsoleted_by);
const emojis  =_.orderBy(filteredEmojis, "sort_order"))

const codeToEmoji = (code: any) => {
    // code = unified
    return String.fromCodePoint(parseInt(code, 16));
 }
```

it's my code, i'm using in React Native to create an Emoji Picker. This bug is occurring in android phone

**Comment by iamcal** [comment]
the issue is that the `unified` field does not just contain a single codepoint, for example "HASH KEY" has a value of `"0023-FE0F-20E3"`. to make your code work correctly:

```
const codeToEmoji = (code: any) => {
    // code = unified
    var codes = code.split('-');
    var buffer = '';
    for (var i=0; i<codes.length; i++){
      buffer += String.fromCodePoint(parseInt(codes[i], 16));
    }
    return buffer;
}
```

**Comment by pedrohenriquebraga** [comment]
@iamcal This code works! But it generated another bug in some emojis (not all)

![Screenshot_20210623-191232_Expo Go.jpg](https://user-images.githubusercontent.com/62728884/123174899-3fa5b600-d457-11eb-9f9e-e18a75b2e43e.jpg)

**Comment by iamcal** [comment]
It looks like the native rendering method you're using is unable to support certain codepoints, so they're appearing as their fallback (which is a sequence of images).

**Comment by pedrohenriquebraga** [comment]
@iamcal is there any way to solve this?

**Comment by pedrohenriquebraga** [comment]
@iamcal is there any way to solve this?

**Comment by iamcal** [comment]
I'm not sure what you're trying to do.

This project is a library of data to use in other applications. You should probably start with something higher level that's closer to whatever you're trying to accomplish. Maybe this is closer to what you're looking for: https://github.com/iamcal/js-emoji
