### ISSUE TITLE
Android 12 Emojis

### ISSUE THREAD

**Issue by P5ina** [iamcal/emoji-data#200]
On android 12 package emoji looks like this: 
![image](https://user-images.githubusercontent.com/44378225/133036355-ce790366-b202-4b4d-a485-adc29ab2fa57.png)
But here package emoji is from android 8.0:
![image](https://user-images.githubusercontent.com/44378225/133036555-3cddbbc6-93b3-4488-b972-4f38ab3896dc.png)

**Comment by stof** [comment]
The update to the new google emojis shipped in Android 12 is part of #201

**Comment by stof** [comment]
this is now released in version 14.0
