### ISSUE TITLE
Emoji 15.0 support

### ISSUE THREAD

**Issue by afontenot** [iamcal/emoji-data#216]
- [x] [Noto Emoji](https://github.com/googlefonts/noto-emoji/pull/401)
- [ ] [Twemoji](https://github.com/twitter/twemoji/issues/570) - may not deliver soon because of ongoing issues at Twitter
- [x] Apple - 15.0 support in iOS 16.4
- [x] Facebook - 15.0 now available

Maybe this is a "wait and see" thing because of Twitter, but I thought I'd file a bug for tracking purposes anyway.

**Comment by stof** [comment]
According to https://blog.emojipedia.org/first-look-new-emojis-in-ios-16-4/, the new emojis are available in iOS 16.4 beta

**Comment by afontenot** [comment]
Incidentally, as mentioned in the thread I linked, both the head engineer and lead designer on Twemoji are no longer at Twitter. I think any future for Twemoji is doubtful. Maybe now that the Apple font is available it would be okay to do a release just with Noto + Apple?

**Comment by slweeb** [comment]
Facebook released https://blog.emojipedia.org/facebook-emoji-15-0-changelog/

**Comment by JannesMeyer** [comment]
Apple released as well https://blog.emojipedia.org/ios-16-4-emoji-changelog/

**Comment by afontenot** [comment]
@iamcal all fonts that are still under active development now have 15.0 support, can we have a release containing those for the benefit of downstream emoji-data consumers?

**Comment by yob** [comment]
I haven't tested it yet, but I just noticed v15.0.0 was released in May this year with emoji v15 support
