### ISSUE TITLE
Missing unicode bytes?

### ISSUE THREAD

**Issue by alanhartless** [iamcal/emoji-data#22]
So I'm completely new to the emoji world and trying to get it all worked out :-) We're using this library but finding that we hit an issue where some unicode bytes were missing and thus the emojis weren't found.  

For example:
\xF3\xBE\x93\xAC => Russian flag
\xF3\xBE\x93\xA6 => US flag

Hit the problem because they are used in this tweet that came through the app we're using this library in: https://twitter.com/restorationm/status/617365812769353729

I found the missing emoji listed in https://github.com/atilag/skia-b2g-sgs2/blob/master/emoji/gmojiraw.txt.

Is this something intended, just a one off that we have to deal with, or is there another suggestion?

For now, I simply customized my lists to include those unicode bytes aliased to the equivalents already in the library.

Thanks!!
Alan

**Comment by iamcal** [comment]
those are the (old) google representations.

    \xF3\xBE\x93\xAC  -> U+FE4EC
    \xF3\xBE\x93\xA6 -> U+FE4E6

these are included in the `emoji.json` dataset as google codepoints. you can see them in the google column here: http://unicodey.com/emoji-data/table.htm (search for `:flag-ru:` and `:flag-us:`).

the data is present, so it's probably a case of how you're using it.

**Comment by alanhartless** [comment]
Thanks!

Is there a way I can customize the build script to also include the old representations? The problem is apparently they are still floating out there in some Tweets thus slipping through the cracks when we try to save to a UTF8 database and corrupting the data.  

Thanks!
Alan

**Comment by iamcal** [comment]
Can you explain what you're actually using to process the text? This repo just contains a json file of emoji definitions, no actual processing code.

**Comment by alanhartless** [comment]
Sorry that would help uh? Using your php-emoji library under the emoji-data branch (https://github.com/iamcal/php-emoji) forked and modified to use the latest data here.

**Comment by alanhartless** [comment]
I guess I'm just not for sure how to generate the older Google unicode bytes.  I'll play though.

**Comment by alanhartless** [comment]
Well, just proved I'm a total idiot :-) I fixed it after taking your hint on the emoji.json.  Thanks for the quick responses!

**Comment by iamcal** [comment]
aha! the function you want to use is `emoji_google_to_unified()`. the following code:

    <?php
        include('emoji.php');

        $in = "\xF3\xBE\x93\xAC";

        $unified = emoji_google_to_unified($in);

        $html = emoji_unified_to_html($unified);

        echo "$html\n";

will output the expected flag html:

    <span class="emoji-outer"><span class="emoji-inner emoji1f1f71f1fa"></span></span>
