### ISSUE TITLE
accessing the actual emojis from the json file

### ISSUE THREAD

**Issue by juls0730** [iamcal/emoji-data#220]
Hello, recently I've been building a simple little emoji picker and being able to return the actualy emoji i just picked, is proving to be very hard if not impossible, so I was wondering if it's possible to include the raw emoji in the json file.

kindly, Juls07

**Comment by iamcal** [comment]
A full set of 64px images is about 37MB at the moment, so that would make a huge JSON files.

It's possible to do this yourself, but I won't be adding it to the repo.

**Comment by juls0730** [comment]
@iamcal Oh, if I knew I still had this opened, I would've closed it long ago. I eventually wrote a Python script to scrap the emojis off that table in the HTM file, which was huge. I sincerely apologize for wasting your time, thank you for your response.

**Comment by juls0730** [comment]
no worries lol
