### ISSUE TITLE
Can we get a 30x30 pixel version too (due to the issue with 2078x2078 and we should stay below 2048x2048 texture size?)

### ISSUE THREAD

**Issue by odysoftware** [iamcal/emoji-data#229]
Hey there,

as other also have already found out one has to use the old emoji data (at least when using game engines like unity etc.) because the new emoji data is too big to fit in a 2048x2048 sprite sheet. Using a 4096x4096 texture is too big for old mobile devices. So either we can get 32x32 icons on a 2048y2048 (maybe using less margin) or we create a 30x30 icon file size?. I tried to use the 20x20 icon files but then those icons are really blurry on modern devices. So with 30 we have almost same quality as 32 but we can fit them on a 2048x2048 texture.

Thanks a lot,
Oliver

**Comment by iamcal** [comment]
It's fairly straight forward to create arbitrary sized images, by just taking the 64px sheets and downscaling them in an image editor. This repo (and the packages it creates) are already huge, and adding further sizes is unlikely.

**Comment by sssooonnnggg** [comment]
I've added a tool to solve this, you can achive it at here:
https://github.com/sssooonnnggg/emoji_pot/blob/main/sheet_google_32_pot.png @odysoftware
