### ISSUE TITLE
Updated emoji.json, to include all

### ISSUE THREAD

**Issue by samjoly** [iamcal/emoji-data#236]
Thanks for sharing.
It looks like the emoji.json, doesn't include all emojis. Would it be possible to have an updated version? Or a clue on how to create one so it includes the full list of sheet_apple_32.png item?

Thanks
Sam

**Comment by iamcal** [comment]
Can you describe which emoji you don't think is included in the JSON file?

The images are built _from_ the JSON, so there shouldn't be any differences.

**Comment by samjoly** [comment]
First, thanks for your time. 

I use a Unity plugin to create a map.
https://assetstore.unity.com/packages/tools/gui/simple-emoji-for-textmesh-pro-267889
I feed your image:
https://github.com/iamcal/emoji-data/blob/master/sheet_apple_64.png
and your Json.
https://github.com/iamcal/emoji-data/blob/master/emoji.json

The map created end up missing all the flags, and some other stuff.
![EmojiTMP](https://github.com/iamcal/emoji-data/assets/18342400/82a5ef5a-6841-4b09-b30d-1c993c69ae1a)

![IMG_0952](https://github.com/iamcal/emoji-data/assets/18342400/8740db69-0aa0-47b9-8b0b-32d334fe7fe9)
![Screenshot 2024-01-24 at 10 47 30 PM](https://github.com/iamcal/emoji-data/assets/18342400/6700a8b7-cd46-419f-ab6c-5e550b8d7045)

Of course the plugin could be he issue.

Let me know if t=you have any thoughts.
Thanks

**Comment by samjoly** [comment]
Thanks a lot for looking at it. I'll check there...

**Comment by hippogamesunity** [comment]
@samjoly Hi, as mentioned in Know Issues
"Multi-codepoint emojis are not supported in the current version of TMP"
Flags are most likely contain 2 codepoints, so you can use them with TextMeshPro.

**Comment by samjoly** [comment]
Thanks a lot for the clarification. This TMP limitation is unfortunate; but your plugin still awesome!
Thanks you both : )
