### ISSUE TITLE
How to search for emojis with that have multiple words? Some emojis aren't found at all?

### ISSUE THREAD

**Issue by kg-currenxie** [iamcal/emoji-data#244]
![image](https://github.com/iamcal/emoji-data/assets/48229166/72743da9-df92-44c6-940e-4baa693312c2)
this one should be `face_with_open_eyes_and_hand_over_mouth`

1. how do i search for this? any `-` or `_` would not give any results, or by concatenating the words: Nope :(
![image](https://github.com/iamcal/emoji-data/assets/48229166/5dc11d78-5b58-4a4c-8e8d-7023d63135cc)
![image](https://github.com/iamcal/emoji-data/assets/48229166/6cf06090-c351-496e-9180-2e9d38bdf87d)
![image](https://github.com/iamcal/emoji-data/assets/48229166/b7c7998a-41c6-4993-abf8-403c53445a7b)
![image](https://github.com/iamcal/emoji-data/assets/48229166/ecb0f06d-70ed-4e99-aabc-9297fdb6e0f2)

2. so maybe i can only search by one word? what about `over` or `mouth`? Nope :(
![image](https://github.com/iamcal/emoji-data/assets/48229166/57d5dc9a-1b8d-4769-a73e-9c079853b3d1)
![image](https://github.com/iamcal/emoji-data/assets/48229166/da6108fb-4499-40c2-8dd6-863036f84ce3)

3. also, please consider implementing a show-shortname-on-hover functionality, like Slack. Otherwise, how would I ever learn what my favorite emojis are named?
![image](https://github.com/iamcal/emoji-data/assets/48229166/999083b5-7e55-44d8-90fc-b33c5ae4f3a8)

(PS: Screenshots are from Whatsapp Web, but I see the same result on https://moji-search.herokuapp.com)

**Comment by iamcal** [comment]
I think it just depends on how each of those libraries has implemented search. Here's what happens in Slack (which uses the same data source):

![image](https://github.com/iamcal/emoji-data/assets/173750/646fd859-3d31-4207-a22b-5fe6d5f8bebf)
