### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by olegshilov** [iamcal/emoji-data#30]
Hi. It would be great to see this project in npm registry.

**Comment by iamcal** [comment]
I'm not sure how to do this really. The project does not make sense without the images, and npm does not accept 50MB+ packages

**Comment by SEAPUNK** [comment]
You could have this be a part of the module "build" process: Just before it finishes installing, it runs a build script that downloads the image data into its module dir. Kind of how the Electron package does it:

```
[ivan@alpha ~]$ sudo npm install -g electron-prebuilt
[sudo] password for ivan: 
/usr/bin/electron -> /usr/lib/node_modules/electron-prebuilt/cli.js

> electron-prebuilt@0.36.1 postinstall /usr/lib/node_modules/electron-prebuilt
> node install.js

Downloading electron-v0.36.1-linux-ia32.zip
[============================================>] 100.0% of 38.25 MB (2.68 MB/s)
```

**Comment by SEAPUNK** [comment]
Past that it will be basically about exposing an API that lets you do things with the emoji, e.g. get the JSON, get the file for an emoji, etc.

**Comment by olegshilov** [comment]
@iamcal Yes, you right. There's no need to put this package to npm registry.
But, if you add package.json file to repository, it allows us to install directly from github with `npm i github:iamcal/emoji-data.git`

**Comment by iamcal** [comment]
i've added a version basic package.json file: https://github.com/iamcal/emoji-data/blob/master/package.json

let me know what needs changing, or send a PR
