### ISSUE TITLE
Optimise image data

### ISSUE THREAD

**Issue by morkro** [iamcal/emoji-data#40]
The images are currently quite heavy. How about adding some sort compression? 

For instance the [`sheet_google_64.png`](https://github.com/iamcal/emoji-data/blob/master/sheet_google_64.png) has a total of *3.44MB*. I've run this image through [_TinyPNG_](https://tinypng.com/developers/reference/php) and the result is only 1.00MB. That's a save of **72%**!

What do you think?

**Comment by iamcal** [comment]
This repo provides the images in their original high quality. Quantizing the sheets causes a significant degradation in image quality; they just use too many colors to be reduced to 256 and maintain fidelity. You're welcome to compress the images as much as you find acceptable, but the repo will continue to contain only original quality.

**Comment by porada** [comment]
@iamcal, what’s your opinion on lossless compression, though?

**Comment by iamcal** [comment]
the sheets are already run through `optipng` with the highest search factor (takes a few hours for each release), but if you have a reliable/automatable way of compressing them further, i'm interested!

**Comment by porada** [comment]
I’m confident [ImageOptim](https://imageoptim.com/mac) will deliver better results here, as it makes use of several lossless optimization tools like `optipng` and can be automated. The only downside is that it’s not cross-platform (works only on OS X).

@iamcal, I can integrate this into the pipeline—just let me know if you’re okay with that.

**Comment by iamcal** [comment]
i don't use a mac; it needs to be automated under linux, sorry

**Comment by iamcal** [comment]
Issue #49 is for adding an alternative version of the sheets with indexed colors to make them smaller.
