### ISSUE TITLE
Publish your library to npm

### ISSUE THREAD

**Issue by unimonkiez** [iamcal/emoji-data#41]
Hey, 
First of all, great project.

I've been working on a [library](https://github.com/TimeToKnow/emoji-panel) to display panels of emojies using your data.
As for now, using this library as peer-dependency (because in the future I'll make another libraries like emoji-input and such) and don't won't to include \ pack your data twice.

Peer-dependencies to github pages is not usual, better take it to npm.
Please consider

**Comment by iamcal** [comment]
Similar to issue #21, the problem is that npm does not support packages that contain a ton of binary image data; even just the 64px sheets come out to 17MB

**Comment by iamcal** [comment]
A package also already exists on npm called `emoji-data`, which includes this data file as a vendored dependency: https://www.npmjs.com/package/emoji-data

You can use this repo as a dependency by including the git URL in your own `package.json`

**Comment by unimonkiez** [comment]
npm dependencies are just more clean and you can exclude some files (only the result spritesheets and the data is needed actually) from the registry, and speedup the installation process for my own library, same goes for bower.  
Would really love seeing that!

**Comment by unimonkiez** [comment]
Also your repo has a package json, and even though I installed your repo from github, it still errors ([here's my build log](https://travis-ci.org/TimeToKnow/emoji-panel/builds/127036654)) on `package.json` validation.

**Comment by iamcal** [comment]
i'm not sure about the error you're seeing; sorry

i see you switched your dependency to download from github and that seems like a reasonable interim solution. i've been advised by npm to put the images as a tarball somewhere and have the package download these, rather than including them into the package itself, but that will require a bunch of work

**Comment by unimonkiez** [comment]
Exactly, that what I did in my own project, though you can create another repo which will download the images on installation.
Again, that's work. 
who knows I might find the time to do it myself

**Comment by iamcal** [comment]
After PR #48 we're pretty close - just need to get the namespace now :+1:

**Comment by unimonkiez** [comment]
Hey, how is it going?

**Comment by iamcal** [comment]
it's stalled trying to figure out how to not break things for existing users of the emoji-data package. i guess a new name for the npm package makes sense. any suggestions?

**Comment by unimonkiez** [comment]
Yeah from experience you'll have to get a new name.
`emoji-db`, `emoji-source`, `emoji-datasource`

**Comment by iamcal** [comment]
done! https://www.npmjs.com/package/emoji-datasource

**Comment by unimonkiez** [comment]
Great! testing usage right now.
You should update your `README.md`
