### ISSUE TITLE
Duplicate short name "umbrella"

### ISSUE THREAD

**Issue by alliejones** [iamcal/emoji-data#42]
UMBRELLA (2602) and UMBRELLA WITH RAIN DROPS (2614) both have the short name "umbrella". The second should probably be "umbrella_with_rain_drops".

I see you have plans to check for duplicate short names in general, but I'm happy to make a PR for this if it is helpful.

**Comment by iamcal** [comment]
i'm addressing this in PR #45 which will also add detection (luckily only umbrella is currently broken)

**Comment by iamcal** [comment]
landed in v2.4.2
