### ISSUE TITLE
[feature] Add age to JSON

### ISSUE THREAD

**Issue by darkwinternight** [iamcal/emoji-data#47]
Would be cool if you could add the age to the JSON data, i.e. in which unicode version the emoji was introduced (i.e. 🤑 was introduced with Unicode 8.0).

**Comment by iamcal** [comment]
this is a great idea. the next Unicode version has this data in `emoji-data.txt`, so that will make it easy to include. right now it's a bit difficult

**Comment by iamcal** [comment]
this is added on the emoji4 branch, which will become the next release.

field is called `added_in`
