### ISSUE TITLE
Optimize 64-bit emoji assets with ImageOptim

### ISSUE THREAD

**Issue by johnnyrodgers** [iamcal/emoji-data#54]
The individual emoji assets in the folders like https://github.com/iamcal/emoji-data/tree/master/img-google-64 can be optimized ~15% on average by running them through ImageOptim locally (up to ~50% in some cases).

It would be great if these assets were optimized in the repo rather than having to run them as an extra step.

**Comment by johnnyrodgers** [comment]
I'm using the default lossless ImageOptim settings:

![screen shot 2016-06-08 at 5 24 04 pm](https://cloud.githubusercontent.com/assets/14260/15915413/e4c894ce-2d9d-11e6-9556-c1d980ab2254.png)
![screen shot 2016-06-08 at 5 24 05 pm](https://cloud.githubusercontent.com/assets/14260/15915412/e4c88d30-2d9d-11e6-8810-cf7e682b8286.png)
![screen shot 2016-06-08 at 5 24 02 pm](https://cloud.githubusercontent.com/assets/14260/15915411/e4c855ae-2d9d-11e6-92ae-7f2f9f9dcc3a.png)

**Comment by iamcal** [comment]
the guts of what it's doing can be found here: https://github.com/ImageOptim/ImageOptim/blob/master/imageoptim/File.m#L516

**Comment by iamcal** [comment]
tracking this is PR #55

**Comment by iamcal** [comment]
images on master are now optimized and the new tooling will do this going forward
