### ISSUE TITLE
support facebook emoji

### ISSUE THREAD

**Issue by iamcal** [iamcal/emoji-data#56]
e.g. https://www.facebook.com/images/emoji.php/v5/z88/1/32/1f600.png

**Comment by Crissov** [comment]
Do you have the exact image address syntax to scrape, though?

`https://www.facebook.com/images/emoji.php/v{version number}/{3 random? alphanumeric characters}/{single digit, usually ‘1’}/{decimal pixel width/height, e.g. ‘32’}/{lowercase hexadecimal Unicode position}.png`

**Comment by Crissov** [comment]
I turned that into a [gist](https://gist.github.com/Crissov/5bbf9704995317c20955ab2d0caf1045) which (currently) works. Haven’t tried older versions than `v7`.

**Comment by iamcal** [comment]
messenger images have landed on master, but no facebook.com images yet

**Comment by Crissov** [comment]
I figured it out, I guess. Only the few Unicode 10 emojis are available with `size` set to `128`. Even they are not available at 64 pixels (despite what it says in the source code). Every emoji is available for `16`, `18`, `20`, `24`, `28`, `30` and `32` (except the missing Unicode 10 ones)! To get images larger than 32 by 32 pixels, one can increase the `pixelRatio` to 1.5, 2 or 3 (othere values may work as well). The digit after `emoji.php/v` does not seem to matter at all. Facebook itself seems to be using only `v8` and `v7` currently, though.

**Comment by iamcal** [comment]
good find! i'm building the facebook set now (32, 3x -> 96px source images)

**Comment by iamcal** [comment]
merged in #80 - facebook and messenger images are now supported
