### ISSUE TITLE
Are there any ios libraries that use this emoji-data set?

### ISSUE THREAD

**Issue by dylanjha** [iamcal/emoji-data#64]
This emoji-data, along with js-emoji is working great on the web.
- always store emojis in db in colon syntax: `:smile:`
- use js-emoji to render the emojis easily on any platform
- (on web) - if users enter unicode themselves via the mac emoji keyboard - use js-emoji to convert the unicode into colon syntax
- (on native ios app) When a user enters an emoji directly from an ios native application it needs to be translated into the colon syntax. There are a number of swift libraries that do this, but they all seem incomplete and do not seem to use the this emoji-data set. Are there any known swift or objective-c libraries that use this emoji-data set?

Thank you 🙏  😄

**Comment by iamcal** [comment]
We use it internally at Slack, but it's not built in a way that we could easily open source today

**Comment by dylanjha** [comment]
Great, thank you for the answer. Just to confirm, is this the strategy you use at slack:

* store emojis in colon syntax `:smile:`
* all clients (web, android, ios, etc) use the emoji-data as a data-set and have their own helper libraries to convert the colon syntax into emojis on the client side

Thank you!

**Comment by iamcal** [comment]
Exactly. On the web, we convert everything to images. On iOS we convert natively supported emoji to native characters and other emoji (custom and some outliers) to images.
