### ISSUE TITLE
1F3C7-1F3FC not found

### ISSUE THREAD

**Issue by Azq2** [iamcal/emoji-data#65]
but 1F3C7 is exists
why? ios/osx dont have any skins for 1F3C7?

**Comment by iamcal** [comment]
I'm not sure exactly what you're asking. iOS/OSX had skin tones for `horse-racing` until the most recent version where they removed it. We've not updated to the latest version yet

**Comment by iamcal** [comment]
`1F3C7-1F3FC` is now back (in v2.5.0) for apple, twitter, emojione, messenger and facebook. google/android does not have an image for it
