### ISSUE TITLE
iOS 10.2 emojis

### ISSUE THREAD

**Issue by baum1234** [iamcal/emoji-data#69]
Would be nice to add the iOS 10.2 emojis (missing the bacon emoji *gg*)

**Comment by iamcal** [comment]
this is basically the same as #59 - it's on my todo list, but the explosion of combination images makes the current approach to images a bit infeasible

**Comment by baum1234** [comment]
is there any update coming?

**Comment by Crissov** [comment]
I have added #77 for Emoji 4.0 sequences. Together with #59 for Unicode 9.0 codepoints, this covers all additions (but not other changes) of iOS 10.2, so this issue can probably be closed.

**Comment by iamcal** [comment]
Closing this in favor of #77 which is the same thing
