### ISSUE TITLE
Outdated images in gemoji

### ISSUE THREAD

**Issue by jwheare** [iamcal/emoji-data#7]
/cc @mroth @javan

This is a gemoji issue really, but only pull requests are accepted on that repo, not issues, and I wanted to see if anyone's looked into this.

:hearts::clubs::diamonds::spades:

♥️♣️♦️♠️

^ Those changed in iOS7/Mavericks to not have the card background (new unified versions visible in Safari)

Any idea on the best way to regenerate the emoji images so that a pull request can be sent upstream?

There are several other images that got some tweaks, but can't think which ones right now.

**Comment by iamcal** [comment]
as of pr #11 i'm extracting the apple images myself. we're now using 10.10.3 images
