### ISSUE TITLE
Apple emoji license

### ISSUE THREAD

**Issue by froatsnook** [iamcal/emoji-data#75]
Hey.  Thanks for the useful package!

Do you have any idea how Apple's emojis are licensed?  The results of my google searches don't paint a clear picture.  I'm wondering if it's allowed to use them in an app (e.g. how Whatsapp provides the same emojis on Android and iOS).

**Comment by iamcal** [comment]
There's no explicit license; Apple are the copyright holders. They have (up to now) turned a blind eye to people using the images

**Comment by froatsnook** [comment]
Thanks for the info!
