### ISSUE TITLE
Emoji 4.0+ sequences support

### ISSUE THREAD

**Issue by Crissov** [iamcal/emoji-data#77]
The Unicode standard itself #59 only covers codepoints and their attributes, e.g. `Emoji` and `Emoji_Presentation`. All kind of character sequences that shall result in a single emoji glyph rendering are defined in [Unicode® Technical Report (soon: Standard) #&thinsp;51 _Unicode Emoji_](http://unicode.org/reports/tr51/proposed.html#Emoji_ZWJ_Sequences). This includes the following:

- *presentations*
  * applicable emoji followed by either Variation Selector 15 (`text`) or 16 (`emoji`)
- *flags*
  * an Emoji Flag Sequence is a valid pair of Regional Identifier Symbol Letters (RIS), according to CLDR's implementation of ISO 3166-1
  * an Emoji Tag Sequence for ISO 3166-2 code elements (soon)
  * an Emoji ZWJ Sequence (only Rainbow Flag currently)
- *skin tones* (Emoji Modifier Sequence)
  * applicable base followed by Fitzpatrick modifier
- *genders* and *professions* (Emoji ZWJ Sequence)
  * profession emoji base followed by gender symbol (Female = Venus or Male = Mars, possibly soon Neutral/Ambiguous/Androgynous = Mercury)
  * human emoji base (Man or Woman, possibly soon Adult) followed by profession symbol 

[Emoji 4.0](http://emojipedia.org/emoji-4.0/) released on 22 November 2016 added several sequences that most implementations now support (including iOS since version 10.2 #69 released in December 2016): [emoji-data.txt](http://unicode.org/Public/emoji/4.0/emoji-data.txt). It also switched to [English](http://unicode.org/cldr/charts/dev/annotations/germanic.html) [CLDR short names](http://unicode.org/cldr/charts/dev/annotations/index.html) (usually in lowercase or with initial caps) that may differ from the immutable character names in Unicode (usually in uppercase or with initial caps), e.g. _red heart_ vs. `HEAVY BLACK HEART` for :heart:.

[Emoji 5.0](http://emojipedia.org/emoji-5.0/) will add more sequences around the same time Unicode 10.0 will be released, due in June 2017.

PR #72 changes the Unicode source files accordingly to support Emoji 3.0 and 4.0, but is probably not enough on its own.

**Comment by iamcal** [comment]
PR #78 is working on this

**Comment by iamcal** [comment]
now done in v2.5.0
