### ISSUE TITLE
Keywords

### ISSUE THREAD

**Issue by JustinDrake** [iamcal/emoji-data#83]
The official unicode page http://unicode.org/emoji/charts/emoji-list.html has a list of keywords for each emoji. This is useful for search.

What would be the best way to go about getting those keywords?

**Comment by EtienneLem** [comment]
👋  For [EmojiMart](https://github.com/missive/emoji-mart) we use a third party lib that does just that: https://github.com/muan/emojilib

**Comment by JustinDrake** [comment]
Thank you!
