### ISSUE TITLE
Emojione 3.0

### ISSUE THREAD

**Issue by Crissov** [iamcal/emoji-data#85]
Emojione split off the graphics from the code with version 3, hence a new repository at <https://github.com/Ranks/emojione-assets>. Version 1 assets are is still available at <https://github.com/Ranks/emojione-legacy> and version 2 at <https://github.com/Ranks/emojione/tree/2.2.7>.

**Comment by iamcal** [comment]
i'm currently pinned to 2.2.7 and the images haven't changed _yet_, but i'll need to switch over when the next version of Unicode comes out

**Comment by Crissov** [comment]
We've also created a CC-BY-4.0 fork of version 2 that you may want to include in the future, if it proves successful: http://github.com/EmojiTwo/emojitwo/

**Comment by Crissov** [comment]
They are at 3.1 now and Unicode 10 has been released #90.

**Comment by ai** [comment]
We have EmojiOne 4 now, should we enable EMoji 5 for EmojiOne?

@iamcal do you need any help here?

**Comment by iamcal** [comment]
I'm considering removal of EmojiOne, given the combination of unfavorable licensing terms and low usage.

**Comment by Crissov** [comment]
There at least is an actual license for Emojione graphics, unlike for Apple’s. Moving away from CC-BY certainly affected their popularity for the worse, but how would you determine more usage? 

Anyway, aren’t 128px PNGs sufficient for this project?

**Comment by iamcal** [comment]
i'm determining usage from looking at slack raw data and anecdotal conversations with other consumers of this data.

i misunderstood the new licenses - i did not realize PNGs were still available in high resolution, so i think it continues to make sense to include it. i'll look at upgrading to the latest version 👍

**Comment by endel** [comment]
Hey there! I'd like to use the new Emojis from 2017 such as [mage](https://emojipedia.org/mage/) from EmojiOne. Can I help you guys with this? Cheers!

**Comment by oriolbcn** [comment]
I took the time to do this as we needed it in my company, so you can grab the new images and stuff from the PR, or wait for it to be merged 😄
