### ISSUE TITLE
Duplicated emoji

### ISSUE THREAD

**Issue by nkt** [iamcal/emoji-data#86]
Thanks for your project!
During the upgrade my emoji library I've found a small bug:
```
{ char: '👪', name: 'family', x: 14, y: 20 }
{ char: '👨‍👩‍👦', name: 'man-woman-boy', x: 41, y: 9 }
```

These emojis are completely the same, and `family` already has `man-woman-boy` alias

**Comment by nkt** [comment]
Ah, `family` emoji obsoleted.

**Comment by iamcal** [comment]
👍
