### ISSUE TITLE
You broke the internet!

### ISSUE THREAD

**Issue by unimonkiez** [iamcal/emoji-data#87]
Hey!
I've seen you have released a new minor version 2.5.x, where you split the emojies to different npm packages.
This is a blessing BUT it's a breaking release, should have been a major update (3.0.0).

Updating my package to [this](https://github.com/TimeToKnow/emoji-panel/commit/ed60392eba7bfcda7842c31d25e0079e6f6f0955) solved the issue, though many people came complaining to me 😭

**Comment by iamcal** [comment]
urgh, sorry. i hadn't considered this. the underlying data has not changed in format, just the npm packaging.

i've unpublished `emoji-datasource@2.5.2` and `emoji-datasource@2.5.1`. the latest is now `emoji-datasource@2.4.4`.

i'll bump major version before re-publishing to npm

**Comment by iamcal** [comment]
`emoji-datasource@3.0.0` and `emoji-datasource-*@3.0.0` are now out 👍
