### ISSUE TITLE
Discrepancies in emoji names?

### ISSUE THREAD

**Issue by Rosey** [iamcal/emoji-data#88]
Hello! I'm not sure if this is an issue with this repo or an issue with emoji in general or what the heck. I am comparing the emoji alias definitions here with gemoji's (https://github.com/github/gemoji/blob/master/db/emoji.json)

and some of them don't match? Eg

`:thinking_face:` in emoji-data vs `:thinking:` in gemoji. Or 
`:face_with_cowboy_hat:` in emoji-data vs `:cowboy_hat_face:` in gemoji

This is causing some funny problems for us because we have an autocomplete on the front end but then parse it using gemoji on the back end.

Any ideas? Feel free to close as a wontfix as needed, I just was confused because I can't find anyone else complaining on the internet about emoji naming discrepancies, and I thought it odd there's not a canonical set of alias rules. (or maybe there are but I couldn't find any!)

(PS - prior to some of the newer emoji releases we didn't have this problem. Like all the classic emoji - `:grinning:` `:grimacing:` etc all have the same names on both gemoji and emoji-data)

**Comment by iamcal** [comment]
unfortunately there is no standard for "short names", so it's been up to github and slack to come up with these). i've been basing shortnames of new emoji entirely on the official unicode names.

i think i'll add a step in the build process to ensure the gemoji names are added as aliases to this set

**Comment by Rosey** [comment]
👍 thanks a lot for the quick response!
