### ISSUE TITLE
Update to Unicode 10.0/Emoji 5.0

### ISSUE THREAD

**Issue by pabloleban** [iamcal/emoji-data#90]
Thanks a lot for this awesome project 💙💙💙

**Comment by iamcal** [comment]
this will be a placeholder until at least one vendor has released images and the unicode spec has been finalized

**Comment by pabloleban** [comment]
Im not sure what you call a vendor, but Twitter released the Twemoji update yesterday.

**Comment by pabloleban** [comment]
[Here](https://github.com/twitter/twemoji/commit/55443d4b393cfe8e5a8dfc967663f1e899f9c3f6) is the full commit of the last update of Twemoji.

**Comment by nightpool** [comment]
please take care of this, it's been over 5 months :(

**Comment by iamcal** [comment]
work is happening in PR #100

**Comment by iamcal** [comment]
this has been fixed in PR #100 which will become release 4.0.0
