### ISSUE TITLE
Spritemap: sprites 1px bleeding into other sprites

### ISSUE THREAD

**Issue by pk1m** [iamcal/emoji-data#92]
For emoji-one sheets, for both 32 and 20 sizes, a lot of the emojis bleed into the other by 1px.  Anyone else notice this?  I'll see a an emoji with a 1px border on the side or top etc.

**Comment by r14n** [comment]
I see this with Apple sheets as well

**Comment by wskidmore** [comment]
Any update or ideas on possible solutions?

**Comment by alexander-branevskiy** [comment]
updates?

**Comment by pk1m** [comment]
only solution so far is to recreate the sprite with px spacing

**Comment by NathanBaulch** [comment]
The bleeding issue is especially noticeable for me at 75% and 90% browser zoom and things get really wacky at 300% zoom.
![screenshot](https://contattafiles.s3-us-west-1.amazonaws.com/hq/gBz-3gXlVaPbeiJ/Pasted%20Image%3A%20Sep%2013%2C%202017%20-%2010%3A24%3A57pm)

**Comment by iamcal** [comment]
when i do the next major rev of the emoji data (after iOS 11) i'll add spacing to the sheets. the browsers probably aren't going to fix this, and there's nothing you can do client side, so it's the only way

**Comment by iamcal** [comment]
this has been fixed in PR #100 which will become release 4.0.0
