### ISSUE TITLE
Bad twemoji sprite sheet

### ISSUE THREAD

**Issue by Luchanso** [iamcal/emoji-data#93]
Hi, I found problems/artifacts in sheet_twitter_32.png, you can read more about it https://github.com/missive/emoji-mart/issues/98

This is no one artifacts in twitter emoji:
![image](https://user-images.githubusercontent.com/2098777/28928014-c53bdc92-7874-11e7-9d8d-5f8052a89118.png)

**Comment by iamcal** [comment]
this should get fixed when i fix #92

**Comment by iamcal** [comment]
this has been fixed in PR #100 which will become release 4.0.0

**Comment by Luchanso** [comment]
@iamcal Thank you so much
