### ISSUE TITLE
Names of country flags barely useful

### ISSUE THREAD

**Issue by chadoh** [iamcal/emoji-data#94]
Example data for a country flag emoji:

``` json
{
"name": "REGIONAL INDICATOR SYMBOL LETTERS UY",
"unified": "1F1FA-1F1FE",
"variations": [],
"docomo": null,
"au": null,
"softbank": null,
"google": null,
"image": "1f1fa-1f1fe.png",
"sheet_x": 36,
"sheet_y": 7,
"short_name": "flag-uy",
"short_names": [
"flag-uy"
],
"text": null,
"texts": null,
"category": "Flags",
"sort_order": 243,
"added_in": "6.0",
"has_img_apple": true,
"has_img_google": true,
"has_img_twitter": true,
"has_img_emojione": true,
"has_img_facebook": true,
"has_img_messenger": true
}
```

That `"name": "REGIONAL INDICATOR SYMBOL LETTERS UY"` is causing usability issues with `emoji-mart` (see missive/emoji-mart#96). 

I gather from #20 that you are generating these names automatically. Is there some way I can help you generate more useful names for these flags? A name like "[country name] flag" would be great, though I'd also find just "[country name]" pretty ok!

**Comment by iamcal** [comment]
This is fixed in PR #100 which will be release 4.0.0

The `NAME` property now contains e.g. `Israel Flag` instead of `REGIONAL INDICATOR SYMBOL LETTERS IL`
