### ISSUE TITLE
Lack part of emoji sheet

### ISSUE THREAD

**Issue by m-nagae** [iamcal/emoji-data#96]
I executed `php build_image.php`.  But sheet_apple_64.png lacked part.
Would you please tell me solution?

I using ImageMagick 7.0.7-5.
```
 ~  montage -version
Version: ImageMagick 7.0.7-5 Q16 x86_64 2017-10-03 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules
Delegates (built-in): bzlib freetype jng jpeg ltdl lzma png tiff xml zlib
```

![sheet_apple_64_png_-_emoji-data_-____ideaprojects_emoji-data_](https://user-images.githubusercontent.com/1877680/31171029-5d72d70a-a939-11e7-96f0-3f848e1fa451.png)

**Comment by iamcal** [comment]
it looks like the process died part way through, perhaps? did you run our of disk space during processing
