### ISSUE TITLE
Update for macOS 10.13.1

### ISSUE THREAD

**Issue by samkelleher** [iamcal/emoji-data#99]
Just a request to track the update of the Apple set within emojidata in High Sierra 10.13.1 (released Oct 31st) since it contains about 70 new emoji that are also available in iOS 10.2 

Is including the new items as simple as just running the build script?

**Comment by samkelleher** [comment]
Follow up in #90

**Comment by iamcal** [comment]
i'm starting work on this now

**Comment by iamcal** [comment]
work is happening in PR #100
